# client-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: rps-client-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: rps-client
    template:
        metadata:
            labels:
                app: rps-client
        spec:
            containers:
            - name: rps-client
              image: malsingh/rps-game-client:latest
