# server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: rps-server-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: rps-server
    template:
        metadata:
            labels:
                app: rps-server
        spec:
            containers:
            - name: rps-server
              image: malsingh/rps-game-server:latest
              ports:
              - containerPort: 50051